name: SemiHardcorePlugin
version: '${project.version}'
main: plugin.semihardcoreplugin.SemiHardcorePlugin
api-version: 1.19
commands:
  withdrawheart:
    description: Withdraw hearts
    usage: /withdrawheart <number of hearts>
    aliases: [withdraw]
  revive:
    description: Revive eliminated players (player)
    usage: /revive <playername>
    aliases: [rev]
    permission: op
  reviveplayer:
    description: Revive eliminated players (console)
    usage: /reviveplayer <playername>
    aliases: [revplayer]
    permission: op
  reviveme:
    description: Revive eliminated players (player itself)
    usage: /reviveme <playername>
    aliases: [ revme ]