name: SemiHardcorePlugin
version: '${project.version}'
main: plugin.semihardcoreplugin.SemiHardcorePlugin
api-version: 1.19
commands:
  withdraw:
    description: Withdraw hearts
    usage: /withdraw <number of hearts>
  revive:
    description: Revive eliminated players (player)
    usage: /revive