name: SemiHardcorePlugin
version: '${project.version}'
main: plugin.semihardcoreplugin.SemiHardcorePlugin
api-version: 1.19
commands:
  withdraw:
    description: Withdraw hearts
    usage: /withdraw <number of hearts>
  revive:
    description: Revive eliminated players (player)
    usage: /revive <playername>
    permission: op
  reviveplayer:
    description: Revive eliminated players (console)
    usage: /reviveplayer <playername>
    permission: op
  reviveme:
    description: Revive eliminated players (player itself)
    usage: /reviveme <playername>